2024-11-21 09:27:46,044 [DEBUG] proactor_events.py:634 (__init__) Using proactor: IocpProactor
2024-11-21 09:27:54,688 [INFO] 3afk.py:74 (main) (1/2)当前学习链接为: https://kc.zhixueyun.com/#/study/course/detail/a64006e7-4a39-479c-af1d-5cc76a515f73
2024-11-21 09:27:58,148 [ERROR] 3afk.py:95 (main) 发生错误: 无权限查看该资源
2024-11-21 09:27:58,149 [ERROR] 3afk.py:96 (main) Traceback (most recent call last):
  File "d:\ChinaTelecom\智慧学习自动挂课\course_afk\3afk.py", line 93, in main
    await fm.course_learning(page)
  File "d:\ChinaTelecom\智慧学习自动挂课\course_afk\func_module.py", line 222, in course_learning
    raise Exception(f"无权限查看该资源")
Exception: 无权限查看该资源

2024-11-21 09:27:58,149 [INFO] func_module.py:29 (save_to_file) 写入无权限资源链接.txt完毕

2024-11-21 09:27:58,262 [INFO] 3afk.py:74 (main) (2/2)当前学习链接为: https://kc.zhixueyun.com/#/study/course/detail/0fdf15df-603e-4e00-a53b-fa1aae50e2b3
2024-11-21 09:28:01,706 [ERROR] 3afk.py:95 (main) 发生错误: 无权限查看该资源
2024-11-21 09:28:01,708 [ERROR] 3afk.py:96 (main) Traceback (most recent call last):
  File "d:\ChinaTelecom\智慧学习自动挂课\course_afk\3afk.py", line 93, in main
    await fm.course_learning(page)
  File "d:\ChinaTelecom\智慧学习自动挂课\course_afk\func_module.py", line 222, in course_learning
    raise Exception(f"无权限查看该资源")
Exception: 无权限查看该资源

2024-11-21 09:28:01,708 [INFO] func_module.py:29 (save_to_file) 写入无权限资源链接.txt完毕

2024-11-21 09:28:02,019 [INFO] 3afk.py:126 (main) 自动挂课完成，当前时间为Thu Nov 21 09:28:02 2024
